name: WorldSettings
version: '${project.version}'
main: org.desparodev.worldsettings.WorldSettings
api-version: '1.20'
commands:
  settings:
    description: Открывает меню настроек
    usage: /settings